### ISSUE TITLE
close database

### ISSUE THREAD

**Issue by llo8** [AKoulabukhov/CoreDataModelInteractor#1]
close database необходимо обернуть в defer и вызвать сразу после открытия, иначе если при получении закешированный модели, запрос свалится с ошибкой, база данных не будет закрыта

**Comment by AKoulabukhov** [comment]
Хорошо подмечено :) Спасибо, обновлю

**Comment by AKoulabukhov** [comment]
Fixed in [1.0.1](https://github.com/AKoulabukhov/CoreDataModelInteractor/releases/tag/1.0.1)
